#name: qrefine
channels:
  - conda-forge
dependencies:
  # cctbx essentials
  #- cctbx-nightly::cctbx
  #- cctbx-nightly::cctbx-base
  - cctbx:cctbx=2024.12
  - cctbx:cctbx-base=2024.12
  - chem_data::chem_data
  - phenix-project::probe
  - phenix-project::reduce
  # essentials
  - numpy=1.26
##  - python=3.10
  - "libblas=*=*accelerate"
  - networkx
  - rdkit
  - pymongo
  - ase=3.22.1
  # Calculators
  - mopac
#  - xtb
##  - numba
  # - torchani
##  - pytorch=2.*
